<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Seller;
use App\Models\Product;
use App\Models\Review;
use Illuminate\Support\Facades\Validator;
use App\Services\SupabaseStorageService;

class SellerController extends Controller
{
    protected $supabaseStorage;

    public function __construct(SupabaseStorageService $supabaseStorage)
    {
        $this->supabaseStorage = $supabaseStorage;
    }

    /**
     * Menyimpan seller baru (Registrasi SRS-01).
     * Method 'store()' ini sesuai dengan PDF [cite: 105, 129].
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\JsonResponse
     */

    public function store(Request $request){
        $validator = Validator::make($request->all(),[
            'store_name' => 'required|string|max:255',
            'store_description' => 'nullable|string',
            'pic_name' => 'required|string|max:255',
            'pic_phone' => 'required|string|max:13',
            'pic_email' => 'required|email|unique:sellers,pic_email',
            'pic_address' => 'required|string',
            'pic_rt' => 'required|string|max:3',
            'pic_rw' => 'required|string|max:3',
            'pic_district' => 'required|string',
            'pic_city' => 'required|string',
            'pic_province' => 'required|string',
            'pic_ktp_number' => 'required|string|max:20|unique:sellers,pic_ktp_number',
            'pic_photo' => 'nullable|image|max:2048', 
            'pic_ktp_file' => 'required|file|mimes:jpg,png,pdf|max:5120', 
        ]);

        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()], 422);
        }

        $ktpPath = null;
        $photoPath = null;

        try {
            // Upload files to Supabase Storage
            if ($request->hasFile('pic_ktp_file')) {
                $ktpFile = $request->file('pic_ktp_file');
                $ktpFileName = 'ktp_files/' . uniqid() . '_' . $ktpFile->getClientOriginalName();
                $ktpPath = $this->supabaseStorage->upload($ktpFileName, $ktpFile->getContent());
            }
            
            if ($request->hasFile('pic_photo')) {
                $photoFile = $request->file('pic_photo');
                $photoFileName = 'pic_photos/' . uniqid() . '_' . $photoFile->getClientOriginalName();
                $photoPath = $this->supabaseStorage->upload($photoFileName, $photoFile->getContent());
            }

            // Create seller (UUID auto-generated by HasUuids trait)
            $seller = Seller::create([
                'store_name' => $request->store_name,
                'store_description' => $request->store_description,
                'pic_name' => $request->pic_name,
                'pic_phone' => $request->pic_phone,
                'pic_email' => $request->pic_email,
                'pic_address' => $request->pic_address,
                'pic_rt' => $request->pic_rt,
                'pic_rw' => $request->pic_rw,
                'pic_district' => $request->pic_district,
                'pic_city' => $request->pic_city,
                'pic_province' => $request->pic_province,
                'pic_ktp_number' => $request->pic_ktp_number,
                'pic_ktp_file_path' => $ktpPath,
                'pic_photo_path' => $photoPath,
                // Status 'PENDING' sudah di-set default di migrasi
            ]);

            return response()->json([
                'message' => 'Registrasi berhasil! Data Anda sedang diverifikasi.',
                'seller_id' => $seller->id
            ], 201);

        } catch (\Exception $e) {
            // Cleanup uploaded files if database insert fails
            if ($ktpPath) {
                $this->supabaseStorage->delete($ktpPath);
            }
            if ($photoPath) {
                $this->supabaseStorage->delete($photoPath);
            }
            
            return response()->json([
                'error' => 'Registrasi gagal.', 
                'message' => $e->getMessage()
            ], 500);
        }
    }

    public function show($id) {
        // $seller = Seller::find($id);
        // return response()->json($seller);
    }

    /**
     * Get activation status untuk seller
     * Check apakah seller sudah teraktivasi (User created)
     */
    public function getActivationStatus(Request $request)
    {
        $user = $request->user();
        
        // Jika user role bukan seller, return error
        if ($user->role !== 'seller') {
            return response()->json([
                'message' => 'Akses ditolak. Hanya seller yang bisa check status.'
            ], 403);
        }

        // Get seller data
        $seller = Seller::find($user->seller_id);
        
        if (!$seller) {
            return response()->json([
                'message' => 'Data seller tidak ditemukan.',
                'activated' => false
            ], 404);
        }

        return response()->json([
            'activated' => true,
            'seller' => [
                'id' => $seller->id,
                'store_name' => $seller->store_name,
                'pic_name' => $seller->pic_name,
                'pic_email' => $seller->pic_email,
                'status' => $seller->status
            ]
        ]);
    }

    /**
     * Get seller's products for dashboard
     */
    public function getProducts(Request $request)
    {
        $user = $request->user();
        
        if ($user->role !== 'seller') {
            return response()->json([
                'message' => 'Akses ditolak. Hanya seller yang bisa mengakses.'
            ], 403);
        }

        $seller = Seller::find($user->seller_id);
        
        if (!$seller) {
            return response()->json(['message' => 'Seller not found'], 404);
        }
        
        $products = Product::where('seller_id', $seller->id)
            ->select('id', 'name', 'stock', 'price', 'created_at')
            ->orderBy('name', 'asc')
            ->get();
        
        return response()->json([
            'products' => $products
        ]);
    }
    
    /**
     * Get all reviews for seller's products
     */
    public function getReviews(Request $request)
    {
        $user = $request->user();
        
        if ($user->role !== 'seller') {
            return response()->json([
                'message' => 'Akses ditolak. Hanya seller yang bisa mengakses.'
            ], 403);
        }

        $seller = Seller::find($user->seller_id);
        
        if (!$seller) {
            return response()->json(['message' => 'Seller not found'], 404);
        }
        
        // Get all reviews for seller's products
        $reviews = Review::whereHas('product', function($query) use ($seller) {
            $query->where('seller_id', $seller->id);
        })
        ->select('id', 'product_id', 'rating', 'comment', 'reviewer_name', 'created_at')
        ->with('product:id,name')
        ->get();
        
        return response()->json([
            'reviews' => $reviews
        ]);
    }

    /**
     * Get dashboard statistics
     */
    public function getStats(Request $request)
    {
        $user = $request->user();
        
        if ($user->role !== 'seller') {
            return response()->json([
                'message' => 'Akses ditolak. Hanya seller yang bisa mengakses.'
            ], 403);
        }

        $seller = Seller::find($user->seller_id);
        
        if (!$seller) {
            return response()->json(['message' => 'Seller not found'], 404);
        }
        
        // Get total products
        $totalProducts = Product::where('seller_id', $seller->id)->count();
        
        // Get reviews and calculate stats
        $reviews = Review::whereHas('product', function($query) use ($seller) {
            $query->where('seller_id', $seller->id);
        })->get();
        
        $averageRating = $reviews->count() > 0 
            ? round($reviews->avg('rating'), 1) 
            : 0;
        
        // Count unique reviewers by email
        $totalReviewers = $reviews->unique('reviewer_email')->count();
        
        return response()->json([
            'totalProducts' => $totalProducts,
            'averageRating' => $averageRating,
            'totalReviewers' => $totalReviewers
        ]);
    }

    /**
     * Get comprehensive dashboard data (SRS-MartPlace-08)
     * - Sebaran jumlah stok per produk
     * - Sebaran nilai rating per produk
     * - Sebaran pemberi rating berdasarkan lokasi provinsi
     */
    public function getDashboardData(Request $request)
    {
        $user = $request->user();
        
        if ($user->role !== 'seller') {
            return response()->json([
                'message' => 'Akses ditolak. Hanya seller yang bisa mengakses.'
            ], 403);
        }

        $seller = Seller::find($user->seller_id);
        
        if (!$seller) {
            return response()->json(['message' => 'Seller not found'], 404);
        }

        // 1. Sebaran Stok Per Produk
        $productStocks = Product::where('seller_id', $seller->id)
            ->with(['images' => function($query) {
                $query->where('is_primary', true)->orWhere(function($q) {
                    $q->orderBy('created_at', 'asc');
                });
            }])
            ->select('id', 'name', 'stock')
            ->orderBy('stock', 'desc')
            ->get()
            ->map(function($product) {
                $firstImage = $product->images->first();
                return [
                    'id' => $product->id,
                    'name' => $product->name,
                    'stock' => $product->stock,
                    'image' => $firstImage ? $firstImage->image_url : null
                ];
            });

        // 2. Sebaran Rating Per Produk (rata-rata rating tiap produk)
        $productRatings = Product::where('seller_id', $seller->id)
            ->with(['images' => function($query) {
                $query->where('is_primary', true)->orWhere(function($q) {
                    $q->orderBy('created_at', 'asc');
                });
            }])
            ->withCount('reviews')
            ->withAvg('reviews', 'rating')
            ->get()
            ->filter(function($product) {
                return $product->reviews_count > 0;
            })
            ->sortByDesc('reviews_avg_rating')
            ->values()
            ->map(function($product) {
                $firstImage = $product->images->first();
                return [
                    'id' => $product->id,
                    'name' => $product->name,
                    'rating' => round($product->reviews_avg_rating, 1),
                    'review_count' => $product->reviews_count,
                    'image' => $firstImage ? $firstImage->image_url : null
                ];
            });

        // 3. Sebaran Reviewer Berdasarkan Provinsi
        $reviewersByProvince = Review::whereHas('product', function($query) use ($seller) {
                $query->where('seller_id', $seller->id);
            })
            ->select('reviewer_province')
            ->selectRaw('COUNT(DISTINCT reviewer_email) as total_reviewers')
            ->groupBy('reviewer_province')
            ->orderBy('total_reviewers', 'desc')
            ->limit(10) // Top 10 provinsi
            ->get()
            ->map(function($item) {
                return [
                    'province' => $item->reviewer_province,
                    'total' => $item->total_reviewers
                ];
            });

        // Summary Stats
        $totalProducts = Product::where('seller_id', $seller->id)->count();
        $totalStock = Product::where('seller_id', $seller->id)->sum('stock');
        
        $reviews = Review::whereHas('product', function($query) use ($seller) {
            $query->where('seller_id', $seller->id);
        })->get();
        
        $averageRating = $reviews->count() > 0 ? round($reviews->avg('rating'), 1) : 0;
        $totalReviewers = $reviews->unique('reviewer_email')->count();
        $totalReviews = $reviews->count();

        return response()->json([
            'summary' => [
                'totalProducts' => $totalProducts,
                'totalStock' => $totalStock,
                'averageRating' => $averageRating,
                'totalReviewers' => $totalReviewers,
                'totalReviews' => $totalReviews
            ],
            'productStocks' => $productStocks,
            'productRatings' => $productRatings,
            'reviewersByProvince' => $reviewersByProvince
        ]);
    }
}