<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Seller;
use App\Models\Product;
use App\Models\Review;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Log;
use App\Services\SupabaseStorageService;
use Mpdf\Mpdf;

class SellerController extends Controller
{
    protected $supabaseStorage;

    public function __construct(SupabaseStorageService $supabaseStorage)
    {
        $this->supabaseStorage = $supabaseStorage;
    }

    /**
     * Menyimpan seller baru (Registrasi SRS-01).
     * Method 'store()' ini sesuai dengan PDF [cite: 105, 129].
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\JsonResponse
     */

    public function store(Request $request){
        $validator = Validator::make($request->all(),[
            'store_name' => 'required|string|max:255',
            'store_description' => 'nullable|string',
            'pic_name' => 'required|string|max:255',
            'pic_phone' => 'required|string|max:13',
            'pic_email' => 'required|email|unique:sellers,pic_email',
            'pic_address' => 'required|string',
            'pic_rt' => 'required|string|max:3',
            'pic_rw' => 'required|string|max:3',
            'pic_district' => 'required|string',
            'pic_city' => 'required|string',
            'pic_province' => 'required|string',
            'pic_ktp_number' => 'required|string|max:20|unique:sellers,pic_ktp_number',
            'pic_photo' => 'nullable|image|max:2048', 
            'pic_ktp_file' => 'required|file|mimes:jpg,png,pdf|max:5120', 
        ]);

        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()], 422);
        }

        $ktpPath = null;
        $photoPath = null;

        try {
            // Upload files to Supabase Storage
            if ($request->hasFile('pic_ktp_file')) {
                $ktpFile = $request->file('pic_ktp_file');
                $ktpFileName = 'ktp_files/' . uniqid() . '_' . $ktpFile->getClientOriginalName();
                $ktpPath = $this->supabaseStorage->upload($ktpFileName, $ktpFile->getContent());
            }
            
            if ($request->hasFile('pic_photo')) {
                $photoFile = $request->file('pic_photo');
                $photoFileName = 'pic_photos/' . uniqid() . '_' . $photoFile->getClientOriginalName();
                $photoPath = $this->supabaseStorage->upload($photoFileName, $photoFile->getContent());
            }

            // Create seller (UUID auto-generated by HasUuids trait)
            $seller = Seller::create([
                'store_name' => $request->store_name,
                'store_description' => $request->store_description,
                'pic_name' => $request->pic_name,
                'pic_phone' => $request->pic_phone,
                'pic_email' => $request->pic_email,
                'pic_address' => $request->pic_address,
                'pic_rt' => $request->pic_rt,
                'pic_rw' => $request->pic_rw,
                'pic_district' => $request->pic_district,
                'pic_city' => $request->pic_city,
                'pic_province' => $request->pic_province,
                'pic_ktp_number' => $request->pic_ktp_number,
                'pic_ktp_file_path' => $ktpPath,
                'pic_photo_path' => $photoPath,
                // Status 'PENDING' sudah di-set default di migrasi
            ]);

            return response()->json([
                'message' => 'Registrasi berhasil! Data Anda sedang diverifikasi.',
                'seller_id' => $seller->id
            ], 201);

        } catch (\Exception $e) {
            // Cleanup uploaded files if database insert fails
            if ($ktpPath) {
                $this->supabaseStorage->delete($ktpPath);
            }
            if ($photoPath) {
                $this->supabaseStorage->delete($photoPath);
            }
            
            return response()->json([
                'error' => 'Registrasi gagal.', 
                'message' => $e->getMessage()
            ], 500);
        }
    }

    public function show($id) {
        // $seller = Seller::find($id);
        // return response()->json($seller);
    }

    /**
     * Get activation status untuk seller
     * Check apakah seller sudah teraktivasi (User created)
     */
    public function getActivationStatus(Request $request)
    {
        $user = $request->user();
        
        // Jika user role bukan seller, return error
        if ($user->role !== 'seller') {
            return response()->json([
                'message' => 'Akses ditolak. Hanya seller yang bisa check status.'
            ], 403);
        }

        // Get seller data
        $seller = Seller::find($user->seller_id);
        
        if (!$seller) {
            return response()->json([
                'message' => 'Data seller tidak ditemukan.',
                'activated' => false
            ], 404);
        }

        return response()->json([
            'activated' => true,
            'seller' => [
                'id' => $seller->id,
                'store_name' => $seller->store_name,
                'pic_name' => $seller->pic_name,
                'pic_email' => $seller->pic_email,
                'status' => $seller->status
            ]
        ]);
    }

    /**
     * Get seller's products for dashboard
     */
    public function getProducts(Request $request)
    {
        $user = $request->user();
        
        if ($user->role !== 'seller') {
            return response()->json([
                'message' => 'Akses ditolak. Hanya seller yang bisa mengakses.'
            ], 403);
        }

        $seller = Seller::find($user->seller_id);
        
        if (!$seller) {
            return response()->json(['message' => 'Seller not found'], 404);
        }
        
        $products = Product::where('seller_id', $seller->id)
            ->select('id', 'name', 'stock', 'price', 'created_at')
            ->orderBy('name', 'asc')
            ->get();
        
        return response()->json([
            'products' => $products
        ]);
    }
    
    /**
     * Get all reviews for seller's products
     */
    public function getReviews(Request $request)
    {
        $user = $request->user();
        
        if ($user->role !== 'seller') {
            return response()->json([
                'message' => 'Akses ditolak. Hanya seller yang bisa mengakses.'
            ], 403);
        }

        $seller = Seller::find($user->seller_id);
        
        if (!$seller) {
            return response()->json(['message' => 'Seller not found'], 404);
        }
        
        // Get all reviews for seller's products
        $reviews = Review::whereHas('product', function($query) use ($seller) {
            $query->where('seller_id', $seller->id);
        })
        ->select('id', 'product_id', 'rating', 'comment', 'reviewer_name', 'created_at')
        ->with('product:id,name')
        ->get();
        
        return response()->json([
            'reviews' => $reviews
        ]);
    }

    /**
     * Get dashboard statistics
     */
    public function getStats(Request $request)
    {
        $user = $request->user();
        
        if ($user->role !== 'seller') {
            return response()->json([
                'message' => 'Akses ditolak. Hanya seller yang bisa mengakses.'
            ], 403);
        }

        $seller = Seller::find($user->seller_id);
        
        if (!$seller) {
            return response()->json(['message' => 'Seller not found'], 404);
        }
        
        // Get total products
        $totalProducts = Product::where('seller_id', $seller->id)->count();
        
        // Get reviews and calculate stats
        $reviews = Review::whereHas('product', function($query) use ($seller) {
            $query->where('seller_id', $seller->id);
        })->get();
        
        $averageRating = $reviews->count() > 0 
            ? round($reviews->avg('rating'), 1) 
            : 0;
        
        // Count unique reviewers by email
        $totalReviewers = $reviews->unique('reviewer_email')->count();
        
        return response()->json([
            'totalProducts' => $totalProducts,
            'averageRating' => $averageRating,
            'totalReviewers' => $totalReviewers
        ]);
    }

    /**
     * Get comprehensive dashboard data (SRS-MartPlace-08)
     * - Sebaran jumlah stok per produk
     * - Sebaran nilai rating per produk
     * - Sebaran pemberi rating berdasarkan lokasi provinsi
     */
    public function getDashboardData(Request $request)
    {
        $user = $request->user();
        
        if ($user->role !== 'seller') {
            return response()->json([
                'message' => 'Akses ditolak. Hanya seller yang bisa mengakses.'
            ], 403);
        }

        $seller = Seller::find($user->seller_id);
        
        if (!$seller) {
            return response()->json(['message' => 'Seller not found'], 404);
        }

        // 1. Sebaran Stok Per Produk
        $productStocks = Product::where('seller_id', $seller->id)
            ->with(['images' => function($query) {
                $query->orderBy('is_primary', 'desc')->orderBy('created_at', 'asc');
            }, 'category', 'seller', 'reviews' => function($query) {
                $query->orderBy('created_at', 'desc');
            }])
            ->withCount('reviews')
            ->withAvg('reviews', 'rating')
            ->orderBy('stock', 'desc')
            ->get()
            ->map(function($product) {
                $firstImage = $product->images->first();
                $allImages = $product->images->map(function($img) {
                    return [
                        'id' => $img->id,
                        'image_url' => $img->image_url,
                        'is_primary' => $img->is_primary
                    ];
                });
                
                $reviews = $product->reviews->map(function($review) {
                    return [
                        'id' => $review->id,
                        'rating' => $review->rating,
                        'comment' => $review->comment,
                        'reviewer_name' => $review->reviewer_name,
                        'reviewer_email' => $review->reviewer_email,
                        'reviewer_province' => $review->reviewer_province,
                        'created_at' => $review->created_at,
                        'updated_at' => $review->updated_at
                    ];
                });
                
                return [
                    'id' => $product->id,
                    'name' => $product->name,
                    'description' => $product->description,
                    'price' => $product->price,
                    'stock' => $product->stock,
                    'condition' => $product->condition,
                    'location' => $product->location,
                    'status' => $product->status,
                    'weight' => $product->weight,
                    'category' => $product->category ? [
                        'id' => $product->category->id,
                        'name' => $product->category->name
                    ] : null,
                    'seller' => $product->seller ? [
                        'id' => $product->seller->id,
                        'store_name' => $product->seller->store_name
                    ] : null,
                    'reviews_avg_rating' => $product->reviews_avg_rating,
                    'reviews_count' => $product->reviews_count,
                    'image' => $firstImage ? $firstImage->image_url : null,
                    'images' => $allImages,
                    'reviews' => $reviews,
                    'created_at' => $product->created_at,
                    'updated_at' => $product->updated_at
                ];
            });

        // 2. Sebaran Rating Per Produk (rata-rata rating tiap produk)
        $productRatings = Product::where('seller_id', $seller->id)
            ->with(['images' => function($query) {
                $query->where('is_primary', true)->orWhere(function($q) {
                    $q->orderBy('created_at', 'asc');
                });
            }])
            ->withCount('reviews')
            ->withAvg('reviews', 'rating')
            ->get()
            ->filter(function($product) {
                return $product->reviews_count > 0;
            })
            ->sortByDesc('reviews_avg_rating')
            ->values()
            ->map(function($product) {
                $firstImage = $product->images->first();
                return [
                    'id' => $product->id,
                    'name' => $product->name,
                    'rating' => round($product->reviews_avg_rating, 1),
                    'review_count' => $product->reviews_count,
                    'image' => $firstImage ? $firstImage->image_url : null
                ];
            });

        // 3. Sebaran Reviewer Berdasarkan Provinsi
        $reviewersByProvince = Review::whereHas('product', function($query) use ($seller) {
                $query->where('seller_id', $seller->id);
            })
            ->select('reviewer_province')
            ->selectRaw('COUNT(DISTINCT reviewer_email) as total_reviewers')
            ->groupBy('reviewer_province')
            ->orderBy('total_reviewers', 'desc')
            // ->limit(10) // Top 10 provinsi
            ->get()
            ->map(function($item) {
                return [
                    'province' => $item->reviewer_province,
                    'total' => $item->total_reviewers
                ];
            });

        // Summary Stats
        $totalProducts = Product::where('seller_id', $seller->id)->count();
        $totalStock = Product::where('seller_id', $seller->id)->sum('stock');
        
        $reviews = Review::whereHas('product', function($query) use ($seller) {
            $query->where('seller_id', $seller->id);
        })->get();
        
        $averageRating = $reviews->count() > 0 ? round($reviews->avg('rating'), 1) : 0;
        $totalReviewers = $reviews->unique('reviewer_email')->count();
        $totalReviews = $reviews->count();

        return response()->json([
            'summary' => [
                'totalProducts' => $totalProducts,
                'totalStock' => $totalStock,
                'averageRating' => $averageRating,
                'totalReviewers' => $totalReviewers,
                'totalReviews' => $totalReviews
            ],
            'productStocks' => $productStocks,
            'productRatings' => $productRatings,
            'reviewersByProvince' => $reviewersByProvince
        ]);
    }

    /**
     * Get Report Data for Preview (JSON)
     */
    public function getReportData(Request $request, $type)
    {
        $user = $request->user();
        
        if ($user->role !== 'seller') {
            return response()->json(['message' => 'Akses ditolak'], 403);
        }
        
        $seller = Seller::find($user->seller_id);
        
        if (!$seller) {
            return response()->json(['message' => 'Seller not found'], 404);
        }

        try {
            $products = [];
            
            switch($type) {
                case 'stock':
                    $products = Product::where('seller_id', $seller->id)
                        ->with('category:id,name')
                        ->withAvg('reviews', 'rating')
                        ->orderBy('stock', 'desc')
                        ->get()
                        ->map(function($product, $index) {
                            return [
                                'id' => $product->id,
                                'no' => $index + 1,
                                'nama_produk' => $product->name,
                                'kategori' => $product->category->name ?? '-',
                                'harga' => $product->price,
                                'stok' => $product->stock,
                                'rating' => round($product->reviews_avg_rating ?? 0, 1)
                            ];
                        });
                    break;

                case 'rating':
                    $products = Product::where('seller_id', $seller->id)
                        ->with('category:id,name')
                        ->withCount('reviews')
                        ->withAvg('reviews', 'rating')
                        ->get()
                        ->filter(fn($p) => $p->reviews_count > 0)
                        ->sortByDesc('reviews_avg_rating')
                        ->values()
                        ->map(function($product, $index) {
                            return [
                                'id' => $product->id,
                                'no' => $index + 1,
                                'nama_produk' => $product->name,
                                'kategori' => $product->category->name ?? '-',
                                'harga' => $product->price,
                                'stok' => $product->stock,
                                'rating' => round($product->reviews_avg_rating ?? 0, 1),
                                'total_reviews' => $product->reviews_count
                            ];
                        });
                    break;

                case 'reorder':
                    $products = Product::where('seller_id', $seller->id)
                        ->with('category:id,name')
                        ->where('stock', '<', 2)
                        ->orderBy('category_id', 'asc')
                        ->orderBy('name', 'asc')
                        ->get()
                        ->map(function($product, $index) {
                            return [
                                'id' => $product->id,
                                'no' => $index + 1,
                                'nama_produk' => $product->name,
                                'kategori' => $product->category->name ?? '-',
                                'harga' => $product->price,
                                'stok' => $product->stock
                            ];
                        });
                    break;

                default:
                    return response()->json(['message' => 'Invalid report type'], 400);
            }

            return response()->json([
                'success' => true,
                'data' => $products,
                'generated_by' => $user->name,
                'generated_date' => now()->format('d F Y')
            ]);

        } catch (\Exception $e) {
            Log::error('Report Data Error: ' . $e->getMessage());
            return response()->json([
                'success' => false,
                'message' => 'Failed to fetch report data'
            ], 500);
        }
    }

    /**
     * Generate PDF Report
     */
    public function generateReport(Request $request, $type)
    {
        $user = $request->user();
        
        // Check if user is seller
        if ($user->role !== 'seller') {
            return response()->json(['message' => 'Akses ditolak. Hanya seller yang bisa mengakses.'], 403);
        }
        
        $seller = Seller::find($user->seller_id);
        
        if (!$seller) {
            return response()->json(['message' => 'Seller not found'], 404);
        }

        try {
            // Get logo as base64
            $logoPath = public_path('logo.png');
            $logoData = '';
            if (file_exists($logoPath)) {
                $logoData = 'data:image/png;base64,' . base64_encode(file_get_contents($logoPath));
            }

            // Fetch products based on type
            $products = [];
            $title = '';
            $columns = [];

            switch($type) {
                case 'stock':
                    $products = Product::where('seller_id', $seller->id)
                        ->with('category:id,name')
                        ->withAvg('reviews', 'rating')
                        ->orderBy('stock', 'desc')
                        ->get();
                    $title = 'Laporan Daftar Produk Berdasarkan Stock';
                    $columns = ['No', 'Produk', 'Kategori', 'Harga', 'Rating', 'Stock'];
                    break;

                case 'rating':
                    $products = Product::where('seller_id', $seller->id)
                        ->with('category:id,name')
                        ->withCount('reviews')
                        ->withAvg('reviews', 'rating')
                        ->get()
                        ->filter(fn($p) => $p->reviews_count > 0)
                        ->sortByDesc('reviews_avg_rating')
                        ->values();
                    $title = 'Laporan Daftar Produk Berdasarkan Rating';
                    $columns = ['No', 'Produk', 'Kategori', 'Harga', 'Stock', 'Rating'];
                    break;

                case 'reorder':
                    $products = Product::where('seller_id', $seller->id)
                        ->with('category:id,name')
                        ->where('stock', '<', 2)
                        ->orderBy('category_id', 'asc')
                        ->orderBy('name', 'asc')
                        ->get();
                    $title = 'Laporan Daftar Produk Segera Dipesan';
                    $columns = ['No', 'Produk', 'Kategori', 'Harga', 'Stock'];
                    break;

                default:
                    return response()->json(['message' => 'Invalid report type'], 400);
            }

            // Build HTML
            $html = '
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="utf-8">
                <title>' . $title . '</title>
                <style>
                    @page {
                        margin: 20mm 15mm;
                    }
                    
                    body {
                        font-family: "DejaVu Sans", Arial, sans-serif;
                        font-size: 10px;
                        color: #1a1a1a;
                        margin: 0;
                        padding: 0;
                        line-height: 1.5;
                    }
                    
                    .header {
                        background: #7A57B3;
                        color: white;
                        padding: 20px 25px;
                        margin-bottom: 20px;
                        border-radius: 6px;
                        box-shadow: 0 2px 6px rgba(122, 87, 179, 0.15);
                        display: flex;
                        align-items: center;
                        gap: 15px;
                    }
                    
                    .logo {
                        width: 48px;
                        height: 48px;
                        border-radius: 8px;
                        flex-shrink: 0;
                    }
                    
                    .company-info h1 {
                        margin: 0;
                        font-size: 16px;
                        font-weight: 700;
                        letter-spacing: 0.3px;
                    }
                    
                    .company-info p {
                        margin: 2px 0 0 0;
                        font-size: 9px;
                        opacity: 0.9;
                    }
                    
                    .meta-info {
                        background: #f7fafc;
                        border: 1px solid #e2e8f0;
                        border-radius: 6px;
                        padding: 12px 15px;
                        margin: 15px 0;
                        display: flex;
                        justify-content: space-between;
                        align-items: center;
                    }
                    
                    .meta-item {
                        font-size: 9px;
                        color: #4a5568;
                    }
                    
                    .meta-item strong {
                        display: block;
                        font-weight: 600;
                        color: #2d3748;
                        margin-top: 2px;
                    }
                    
                    table {
                        width: 100%;
                        border-collapse: collapse;
                        margin-top: 10px;
                    }
                    
                    th {
                        background: #7A57B3;
                        color: white;
                        padding: 10px;
                        text-align: left;
                        font-weight: 600;
                        font-size: 9px;
                        border: 1px solid #7A57B3;
                    }
                    
                    td {
                        padding: 8px 10px;
                        border: 1px solid #e2e8f0;
                        font-size: 9px;
                    }
                    
                    tbody tr:nth-child(even) {
                        background-color: #f8f9fa;
                    }
                    
                    tbody tr:hover {
                        background-color: #f0f4ff;
                    }
                    
                    .text-center {
                        text-align: center;
                    }
                    
                    .text-right {
                        text-align: right;
                    }
                    
                    .footer {
                        margin-top: 30px;
                        padding-top: 15px;
                        border-top: 2px solid #7A57B3;
                        font-size: 8px;
                        color: #718096;
                        display: flex;
                        justify-content: space-between;
                    }
                </style>
            </head>
            <body>
                <div class="header">
                    ' . ($logoData ? '<img src="' . $logoData . '" alt="Logo" class="logo">' : '') . '
                    <div class="company-info">
                        <h1>Astro E-Commerce</h1>
                        <p>Laporan Seller - ' . htmlspecialchars($seller->store_name) . '</p>
                    </div>
                </div>
                
                <h2 style="text-align: center; margin: 20px 0 10px 0; font-size: 12px; color: #2d3748;">' . htmlspecialchars($title) . '</h2>
                
                <div class="meta-info">
                    <div class="meta-item">
                        <span>Tanggal dibuat</span>
                        <strong>' . now()->format('d F Y') . ' oleh ' . htmlspecialchars($user->name) . '</strong>
                    </div>
                    <div class="meta-item" style="text-align: center;">
                        <span>Total Data</span>
                        <strong>' . count($products) . ' Produk</strong>
                    </div>
                    <div class="meta-item">
                        <span>Urutkan</span>
                        <strong>' . ($type === 'stock' ? 'berdasarkan stock' : ($type === 'rating' ? 'berdasarkan rating' : 'berdasarkan kategori dan produk')) . '</strong>
                    </div>
                </div>
                
                <table>
                    <thead>
                        <tr>';
            
            // Add table headers
            foreach ($columns as $column) {
                $html .= '<th>' . $column . '</th>';
            }
            
            $html .= '
                        </tr>
                    </thead>
                    <tbody>';
            
            // Add table rows
            if (count($products) > 0) {
                foreach ($products as $index => $product) {
                    $no = $index + 1;
                    $html .= '<tr>';
                    $html .= '<td class="text-center">' . $no . '</td>';
                    $html .= '<td>' . htmlspecialchars($product->name) . '</td>';
                    $html .= '<td>' . htmlspecialchars($product->category->name ?? '-') . '</td>';
                    $html .= '<td class="text-right">Rp ' . number_format($product->price ?? 0, 0, ',', '.') . '</td>';
                    
                    if ($type === 'stock') {
                        $html .= '<td class="text-center">' . round($product->reviews_avg_rating ?? 0, 1) . '</td>';
                        $html .= '<td class="text-center">' . $product->stock . '</td>';
                    } elseif ($type === 'rating') {
                        $html .= '<td class="text-center">' . $product->stock . '</td>';
                        $html .= '<td class="text-center">' . round($product->reviews_avg_rating ?? 0, 1) . '</td>';
                    } else {
                        $html .= '<td class="text-center">' . $product->stock . '</td>';
                    }
                    
                    $html .= '</tr>';
                }
            } else {
                $html .= '<tr><td colspan="' . count($columns) . '" class="text-center">Tidak ada data</td></tr>';
            }
            
            $html .= '
                    </tbody>
                </table>
                
                <div class="footer">
                    <div>
                        <strong>Astro E-Commerce</strong><br>
                        ***) ' . ($type === 'stock' ? 'urutkan berdasarkan stock' : ($type === 'rating' ? 'urutkan berdasarkan rating' : 'urutkan berdasarkan kategori dan produk'))
                    . '
                    </div>
                    <div style="text-align: right;">
                        <strong>' . htmlspecialchars($seller->store_name) . '</strong><br>
                        Dicetak: ' . now()->format('d F Y H:i') . ' WIB
                    </div>
                </div>
            </body>
            </html>';
            
            // Create mPDF instance
            $mpdf = new Mpdf([
                'mode' => 'utf-8',
                'format' => 'A4',
                'margin_top' => 15,
                'margin_bottom' => 15,
                'margin_left' => 15,
                'margin_right' => 15,
            ]);
            
            $mpdf->WriteHTML($html);
            
            $filename = 'Laporan_' . ucfirst($type) . '_' . str_replace(' ', '_', $seller->store_name) . '_' . now()->format('YmdHis') . '.pdf';
            
            return response($mpdf->Output($filename, 'S'), 200, [
                'Content-Type' => 'application/pdf',
                'Content-Disposition' => 'attachment; filename="' . $filename . '"',
            ]);

        } catch (\Exception $e) {
            Log::error('PDF Generation Error: ' . $e->getMessage());
            return response()->json([
                'message' => 'Failed to generate PDF report',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
